model:
  model_id: meta-llama/Llama-3.1-8B-Instruct
  tokenizer_id: meta-llama/Llama-3.1-8B-Instruct
  pad_token_as_eos: true
  from_pretrained_params:
    torch_dtype: bfloat16
    trust_remote_code: true
    use_cache: false
  gradient_checkpointing: true
  lora:
    enabled: true
    r: 16
    lora_alpha: 32
    lora_dropout: 0.05
    target_modules:
      - q_proj
      - v_proj
    bias: none
    task_type: CAUSAL_LM
    training_mode: qlora
  ipex:
    enabled: true
    optimize_model: false
  prepare_kbit_training: true

data:
  dataset_type: json
  dataset_name: yahma/alpaca-cleaned   # or any instruction‑style dataset
  # data_files: data/datasets-autism.json
  split: train[:100]
  batch_size: 1
  max_length: 1536
  # split_ratio: 0.9
  num_workers: 1
  instruction_style: SFT_llama31

training:
  epochs: 5
  learning_rate: 5e-5
  weight_decay: 0.02
  gradient_accumulation_steps: 4
  save_steps: 500
  output_dir: outputs/llama3.18B_qlora_xpu
  seed: 42
  device: xpu
  clear_xpu_cache: true
  scheduler:
    min_lr: 1e-6
    max_lr: 5e-5
    warmup_steps: 200
    restart_interval: 100
    restart_mult: 1.0

environment:
  CCL_PROCESS_LAUNCHER: none
  TORCH_LLM_ALLREDUCE: 1