training:
  folder: "./data/your_image_folder"
  output_folder: "./outputs/lora_stable-diffusion-1-5-base_xpu"  # Add this line
  trigger_token: "a stunning portrait of scarjo_style"
  epochs: 100
  learning_rate: 4e-4
  image_size: 512

scheduler:
  min_lr: 1e-6
  max_lr: 4e-4
  warmup_steps: 25
  restart_interval: 50
  restart_mult: 1.0

model:
  pretrained_model_name: "stable-diffusion-v1-5/stable-diffusion-v1-5"
  variant: "fp16"
  use_safetensors: true
  safety_checker: null

lora:
  task_type: "TEXT_TO_IMAGE"
  inference_mode: false
  r: 4
  lora_alpha: 8
  target_modules: ["proj_in", "proj_out"]

early_stopping:
  patience: 5